### ISSUE TITLE
Clang build support?

### ISSUE THREAD

**Issue by mintyc** [preshing/turf#1]
Any plans to also support a recent version of clang on linux in addition to gcc?

Thanks for your excellent blog articles and libs.

**Comment by preshing** [comment]
It already works! You just tell CMake which compiler to use. If generating Makefiles, you should specify your desired build configuration as well.

```
$ cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
```

You can do this with any CMake-based project (assuming it compiles).
